.TH "Car" 3 "Wed Apr 6 2022" "'Kinetic Sculpture'" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Car
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <car\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCar\fP ()"
.br
.ti -1c
.RI "\fBCar\fP (std::string)"
.br
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBCar\fP class controls the car and flower
.PP
\fBAuthor\fP
.RS 4
Sedona Thomas 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Car::Car ()"
\fBCar\fP constructor makes a car object 
.SS "Car::Car (std::string _name)"
\fBCar\fP constructor makes a car object
.PP
\fBParameters\fP
.RS 4
\fIname_in\fP the car name 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Car::run ()"
The run method runs the car 
.SS "void Car::setup ()"
The setup method sets up the car 

.SH "Author"
.PP 
Generated automatically by Doxygen for 'Kinetic Sculpture' from the source code\&.
